---
- hosts: localhost
  gather_facts: false
  roles:
    - { role: k8s }
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    image_name: hello-go
    image_tag: latest
    replicas: 4
